# Generated by Django 3.2.5 on 2021-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0004_alter_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('CONTRIBUTOR', 'CONTRIBUTOR')], default='CONTRIBUTOR', max_length=128),
        ),
    ]
