# Generated by Django 3.2.5 on 2021-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0005_auto_20210909_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'COMPLETE')], default='TODO', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('UPGRADE', 'UPGRADE'), ('TASK', 'TASK')], max_length=100),
        ),
    ]
