# Generated by Django 3.2.5 on 2021-09-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0007_alter_contributor_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
    ]
