# Generated by Django 3.2.5 on 2021-09-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0008_remove_comment_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
